services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_ERLANG_COOKIE: mysecretcookie
    ports:
      - "5672:5672"    # AMQP (producers/consumers)
      - "15672:15672"  # Management UI
      - "4369:4369"    # epmd (para clustering)
      - "25672:25672"  # inter-node communication (clustering)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  rabbitmq_data: